### PR TITLE
add docker-compose file for turtl

### PR DESCRIPTION
**Pull request by hechi**
i added a docker-compose.yml file which every one can use on top of your build :) thx do provide a docker image

### CODE REVIEW

**Comment by fredleger** [comment]
Hi,

Thanks for the contribution.
Actually i did it in another way.

- Having this repo for the automated-build of the image
- Contributed to rancher catalog with docker-compose infos (https://github.com/rancher/community-catalog/tree/master/templates/turtl/0)

You may want to check it out because it uses a data-volume to keep your data safer and maybe a better option to you.

If not i will will be please to merge your PR too.

**Comment by hechi** [comment]
Hey @fredleger,

i looked into rancher and it looks really nice but a litte to complex for a private admin how is not running rancher already. And i guess for the community it is easy to do only a `docker-compose up -d` command.
What do you think?

Servus

**Comment by fredleger** [comment]
Hey,

I think there was a missunderstanding here.
My point was not to say that you should use rancher (which is a great product anyway) but that the docker-compose.yml file i did provide in rancher repos (which can be used strait without rancher) is making use of data-volumes for the uploads and rethinkdb data, which is considered to be a better practice than bind mounts.

So i would be pleased to add a docker-compose but why not using data-volumes ? 

Cheers
Frederic

**Comment by hechi** [comment]
Hey,

yes it was ^^ so now with volume container ^^

**Comment by fredleger** [comment]
Perfect. merged !
Thanxs for this contribution.

**Comment by hechi** [comment]
Cool awesome :) thanks to you and keep your work up :)

**Pull request merged**
